apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-go
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: run-the-template
    functionRef:
      name: function-go
    input:
      apiVersion: go.fn.crossplane.io/v1beta1
      kind: Script
      inline: |-
        import "fmt"

        func main() {
          fmt.Printf("%s", "Hello world")
        }
